# Generated by Django 4.2.7 on 2024-01-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_jt', models.AutoField(primary_key=True, serialize=False)),
                ('region_jt', models.CharField(max_length=150)),
                ('nombre_jt', models.CharField(max_length=150)),
                ('capital_jt', models.CharField(max_length=150)),
                ('ciudad_jt', models.CharField(max_length=150)),
            ],
        ),
    ]
