# Generated by Django 4.2.7 on 2024-01-14 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platillos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_jt', models.AutoField(primary_key=True, serialize=False)),
                ('cedula_jt', models.CharField(max_length=10)),
                ('apellido_jt', models.CharField(max_length=150)),
                ('nombre_jt', models.CharField(max_length=150)),
                ('direccion_jt', models.TextField()),
                ('fecha_nacimiento_jt', models.DateField()),
                ('correo_jt', models.EmailField(max_length=254)),
            ],
        ),
    ]
