# Generated by Django 4.2.7 on 2024-01-15 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Platillos', '0003_alter_cliente_nombre_jt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='nombre_jt',
        ),
        migrations.AddField(
            model_name='cliente',
            name='provincia_jt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Platillos.provincia'),
        ),
    ]
