# Generated by Django 4.2.7 on 2024-01-15 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Platillos', '0004_remove_cliente_nombre_jt_cliente_provincia_jt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='provincia_jt',
            new_name='nombre_jt',
        ),
    ]
