# Generated by Django 4.2.7 on 2024-01-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platillos', '0005_rename_provincia_jt_cliente_nombre_jt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nombre_jt',
            field=models.CharField(max_length=150),
        ),
    ]
