# Generated by Django 4.2.7 on 2024-01-15 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Platillos', '0007_rename_id_jt_cliente_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='id',
            new_name='id_jt',
        ),
    ]
