# Generated by Django 4.2.7 on 2024-01-15 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Platillos', '0009_rename_nombre_jt_cliente_nombrecliente_jt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nombreCliente_jt',
            new_name='nombre_jt',
        ),
    ]
