# Generated by Django 4.2.7 on 2024-01-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platillos', '0010_rename_nombrecliente_jt_cliente_nombre_jt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_jt', models.AutoField(primary_key=True, serialize=False)),
                ('nombrePedido_jt', models.CharField(max_length=10)),
                ('fechaPedido_jt', models.DateField()),
                ('horaPedido_jt', models.CharField(max_length=150)),
                ('fotografiaPedido_jt', models.FileField(blank=True, null=True, upload_to='pedidos')),
            ],
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='apellido_jt',
            new_name='apellidoCliente_jt',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='cedula_jt',
            new_name='cedulaCliente_jt',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='correo_jt',
            new_name='correoCliente_jt',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='direccion_jt',
            new_name='direccionCliente_jt',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='fecha_nacimiento_jt',
            new_name='fechaNacimientoCliente_jt',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='id_jt',
            new_name='idCliente_jt',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre_jt',
            new_name='nombreCliente_jt',
        ),
    ]
