# Generated by Django 4.2.7 on 2024-01-16 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Platillos', '0011_pedido_rename_apellido_jt_cliente_apellidocliente_jt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='apellidoCliente_jt',
            new_name='apellido_jt',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='cedulaCliente_jt',
            new_name='cedula_jt',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='correoCliente_jt',
            new_name='correo_jt',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='direccionCliente_jt',
            new_name='direccion_jt',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='fechaNacimientoCliente_jt',
            new_name='fecha_nacimiento_jt',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nombreCliente_jt',
            new_name='nombre_jt',
        ),
    ]
