# Generated by Django 4.2.7 on 2024-01-16 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platillos', '0014_rename_horapedido_jt_pedido_descripcionpedido_jt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='descripcionPedido_jt',
            field=models.TextField(),
        ),
    ]
