# Generated by Django 4.2.7 on 2024-01-16 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platillos', '0015_alter_pedido_descripcionpedido_jt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('idTipo_jt', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTipo_jt', models.CharField(max_length=150)),
                ('descripcionTipo_jt', models.TextField()),
                ('categoriaTipo_jt', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fotografiaPedido_jt',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='nombrePedido_jt',
        ),
        migrations.AddField(
            model_name='pedido',
            name='horaPedido_jt',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
