# Generated by Django 4.2.7 on 2024-01-16 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Platillos', '0022_platillo_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platillo',
            old_name='nombrePLatillo_jt',
            new_name='nombrePlatillo_jt',
        ),
    ]
