# Generated by Django 4.2.7 on 2024-01-16 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Platillos', '0023_rename_nombreplatillo_jt_platillo_nombreplatillo_jt'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='platillo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Platillos.platillo'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Platillos.tipo'),
        ),
    ]
