# Generated by Django 4.2.7 on 2024-01-16 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Platillos', '0024_pedido_platillo_pedido_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('idReceta_jt', models.AutoField(primary_key=True, serialize=False)),
                ('pasosReceta_jt', models.TextField()),
                ('tiempoPreparacion_jt', models.IntegerField()),
                ('dificultadReceta_jt', models.CharField(max_length=50)),
                ('ingrediente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Platillos.ingrediente')),
                ('platillo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Platillos.platillo')),
            ],
        ),
    ]
