# Generated by Django 4.2.7 on 2024-01-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platillos', '0025_receta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
